# 项目信息
site_name: ZJULWind's Blog    # 项目名称
site_url: https://localhost:8000/ 
site_author: ZJULWind         # 作者
# 代码仓库信息
repo_name: ZJULWindCode # 仓库名称
repo_url: https://github.com/ZJULWind/ZJULWind.github.io # 仓库地址


nav: 
  - 首页: 
    - 首页 : home/index.md
    - 朋友们 : home/friend.md
    - Building your website : home/writeup.md

  - 基础课程: 
    - ./fundamental/index.md 
    - 概率论与数理统计 :
      - ./fundamental/gaitong/index.md
      - 常见随机变量的数字特征: fundamental/gaitong/sum.md
      - 5-大数定律和中心极限定理 : fundamental/gaitong/chap05.md
      - 6-数理统计的基本概念 : fundamental/gaitong/chap06.md
      - 7-参数估计 : fundamental/gaitong/chap07.md
      - 8-假设检验 : fundamental/gaitong/chap08.md
    - 数据结构基础 :
      - ./fundamental/FDS/index.md
      - Lec02 Asymptotic Notation : fundamental/FDS/Lec02 Asymptotic Notation.md
      - Lec03 Lists Stack Queue   : fundamental/FDS/Lec03 Lists Stack Queue.md
      - Lec04 Tree                : fundamental/FDS/Lec04 Tree.md
      - Lec05 Heap                : fundamental/FDS/Lec05 Heap.md
      - Lec06 Union Find          : fundamental/FDS/Lec06 Union Find.md
      - Lec07 Graph               : fundamental/FDS/Lec07 Graph.md
      - Lec08 Sorting             : fundamental/FDS/Lec08 Sorting.md
      - Lec09 Hashing             : fundamental/FDS/Lec09 Hashing.md
      - FDS复习向                  : fundamental/FDS/FDS复习.md
  - 专业课程: special/index.md
  - ACEE&Shannon: 
    - ./extra/index.md
    - Stanford CS229  MachineLearning :
      - ./extra/Stanford CS229  MachineLearning/index.md
      - 1 线性回归: ./extra/Stanford CS229  MachineLearning/ML Note1.md
      - 2 GDA及朴素贝叶斯 : ./extra/Stanford CS229  MachineLearning/ML Note2.md
      - 3 SVM : ./extra/Stanford CS229  MachineLearning/ML Note3.md
      - 4 学习理论 : ./extra/Stanford CS229  MachineLearning/ML Note4.md
      - 5 无监督学习 : ./extra/Stanford CS229  MachineLearning/ML Note5.md
    - Stanford EE364A Convex Optimization :
      - ./extra/Stanford EE364A Convex Optimization/index.md
      - Lec01 Introduction : ./extra/Stanford EE364A Convex Optimization/Lec01 Introduction.md
      - Lec02 Convex sets : ./extra/Stanford EE364A Convex Optimization/Lec02 Convex sets.md
      - Lec03 Convex Functions : ./extra/Stanford EE364A Convex Optimization/Lec03 Convex Functions.md
      - Lec04 Convex optimization problems : ./extra/Stanford EE364A Convex Optimization/Lec04 Convex optimization problems.md


theme:
  name: material # 主题名称，Material已经是最优秀的选择了，相信我。
  # custom_dir: material/overrides # 自定义文件夹，对于个别页面，如果你不想使用主题的默认样式，可以在这里进行修改，使用里面的文件覆盖主题的默认文件。具体可以参考material官方文档。
  # logo: static/images/logo.png # logo 图片

  features: # 功能
    - announce.dismiss # 可以叉掉公告的功能

    # - content.action.edit # 编辑按钮，会跳转到你的仓库里编辑当前页面内容
    # - content.action.view # 查看按钮，会跳转到你的仓库里查看当前页面内容
    - content.code.annotate # 代码注释，具体不清楚
    - content.code.copy # 复制代码按钮
    # - content.code.select # 选择代码按钮
    - content.tabs.link # 链接标签
    - content.tooltips # 不太清楚呢这个

    - header.autohide # 自动隐藏header

    - navigation.expand # 默认展开导航栏
    - navigation.footer # 底部导航栏
    - navigation.indexes # 索引按钮可以直接触发文件，而不是只能点击其下属选项浏览，这个功能可以给对应的section提供很好的预览和导航功能
    # - navigation.instant # 瞬间加载 最好注释掉，多语言切换这个会导致跳回首页
    - navigation.instant.prefetch # 预加载
    - navigation.instant.progress # 进度条
    - navigation.path # 导航路径， 目前好像没啥用
    - navigation.prune # 只构建可见的页面
    # - navigation.sections # 导航栏的section
    - navigation.tabs # 顶级索引被作为tab
    - navigation.tabs.sticky # tab始终可见
    - navigation.top # 开启顶部导航栏
    - navigation.tracking # 导航栏跟踪

    - search.highlight # 搜索高亮
    - search.share # 搜索分享
    - search.suggest # 搜索建议

    - toc.follow # 目录跟踪-页面右侧的小目录
    # - toc.integrate # 目录跟踪集成到左侧大目录中

  palette:
    - media: "(prefers-color-scheme)" # 主题颜色
      scheme: slate
      primary: teal
      accent: cyan
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)" # 浅色
      scheme: default
      primary: teal
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" # 深色
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font: # 字体，大概率不需要换
    text: Roboto
    code: Roboto Mono
  # favicon: docs/img/favicon.ico # 网站图标，因为你使用了主题会覆盖之前设置的site_favicon属性，所以在这里最好重新设置一下
  # icon: # 一些用到的icon
  #   logo: logo
  #   previous: fontawesome/solid/angle-left
  #   next: fontawesome/solid/angle-right
  #   tag:
  #     default-tag: fontawesome/solid/tag
  #     hardware-tag: fontawesome/solid/microchip
  #     software-tag: fontawesome/solid/laptop-code



markdown_extensions:
  # Python Markdown
  - abbr # 支持缩写标签，允许你定义缩写词及其解释。 
  - admonition #支持创建带有标题的特殊块，用于提示、注意事项等。
  - attr_list #允许在Markdown元素上添加HTML属性。
  - def_list #支持定义列表的创建。
  - tables # 启用Markdown表格语法。
  - footnotes #支持脚注的创建。
  - md_in_html #允许在HTML块内使用Markdown语法。
  - toc: # 生成一个可点击的目录，
      permalink: true
      toc_depth: 5
      permalink_title: 点击此处可置顶内容
  # - markdown.extensions.nl2br #支持无回车换行
  - markdown.extensions.sane_lists #有序无序列表的一个扩展。
  - markdown.extensions.wikilinks #支持wiki链接

  # Python Markdown Extensions
  - pymdownx.arithmatex: #提供对数学表达式的支持，允许在Markdown中直接使用LaTeX语法。
      generic: true
  - pymdownx.betterem #改进了强调（斜体和粗体）的解析。
  - pymdownx.tabbed: #允许创建标签页，用于在同一位置显示不同的内容块。
      alternate_style: true
  - pymdownx.caret  #添加对插入文本和删除文本的支持。
  - pymdownx.details # 支持创建可折叠的详情块（HTML <details> 和 <summary> 标签）。
  - pymdownx.emoji: #通过名称或代码添加表情符号，支持自定义表情生成器。
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight: #改进代码高亮显示，支持行号、行跨度等特性。
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite #允许在文本中直接高亮代码片段。
  - pymdownx.keys #支持键盘按键的表示。
  - pymdownx.mark #支持高亮标记文本。
  - pymdownx.smartsymbols #自动将某些文本模式转换为符号，如箭头和数学符号。
  - pymdownx.superfences: #提供更强大的代码块功能，支持自定义围栏（fences）和Mermaid图表。
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed: #
      alternate_style: true
  - pymdownx.tasklist: #支持任务列表，允许使用自定义复选框。 
      custom_checkbox: true
  - pymdownx.tilde # 支持删除线和下划线文本。
  - pymdownx.snippets: #允许自动包含其他Markdown文件的内容。
      auto_append:
        - includes/abbreviations.md
  # - mdx_wikilink_plus

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/glightbox.min.css
  - assets/stylesheets/galaxy.css
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css

extra_javascript:
  - assets/javascripts/katex.js 
  - assets/javascripts/mathjax.js
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/katex.min.js  
  - https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.16.7/contrib/auto-render.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # - assets/javascripts/titlechange.js
  - assets/javascripts/glightbox.min.js
  # - assets/javascripts/click.js
  # - assets/javascripts/galaxy.js